### ISSUE TITLE
help!! ionic use this build on ios platform  can't show map

### ISSUE THREAD

**Issue by adoop** [leftstick/angular-amap#1]
ionic use this build on ios platform  can't show map
ionic 1.7.14
help!!

**Comment by leftstick** [comment]
Can u provide more information, i never tried ionic. Not sure why it happend

**Comment by adoop** [comment]
issue was solv      ，on ios you need set style like height :500px

**Comment by leftstick** [comment]
yes, the `width`, `height` should be specified explicitly on `directive`:

![screen shot 2016-06-14 at 12 14 49 pm](https://cloud.githubusercontent.com/assets/1059956/16031063/d5f5f280-3229-11e6-91c5-d6dd092dc0cd.png)

I forgot to mention it as mandatory, will update doc. Thanks
