### ISSUE TITLE
实例怎么多次调用？

### ISSUE THREAD

**Issue by Feather130** [leftstick/angular-amap#10]
模仿您的代码增加了以个折线的功能，但是折线需要多次调用setOptions()方法更新数据，您的最新版本增加了loaded，但这只能调用一次，有什么方法可以多次使用实例呢？
`
import {nullCheck} from '../helper/validate';

import {polyline as polylineTransform} from '../helper/transformer';

export default {

    bindings: {
        options: '<',
        loaded: '&'
    },

    require: {
        mapCtrl: '^ngAmap'
    },

    template: '',

    controller: class {
        constructor($scope, $attrs) {
            this.$scope = $scope;
            this.$attrs = $attrs;
        }
        $onInit() {
            nullCheck(this.options, 'options is required for <polyline>');

            this.mapCtrl
                .mapReady
                .then(() => {
                    const polyline = this.polyline = polylineTransform(this.options, 'options');
                    polyline.setMap(this.mapCtrl.getMap());
                    this.loaded({
                        polyline
                    });
                    this.$scope.$apply();
                    return polyline;
                })
        }
        $onDestroy() {
            this.polyline.setMap(null);
        }
    }
}
`
能提一些建议吗？

**Comment by leftstick** [comment]
首先你得明确`loaded`的目的，它是一个事件，通知外部程序`polyline`已经创建完毕，并把`polyline`实例传递给外部程序。

那么既然`loaded`事件已经把`polyline`实例通知到外部程序了，你在外部拿到实例，想调用多少次`setOptions`还不是随便你么？

所以你是想在外部调用的时候控制多次`setOptions`还是就像在插件内部多次调用？

**Comment by Feather130** [comment]
外部调用
就是在开始时调用setOptions，然后在每次人为更换数据后再次调用setOptions

**Comment by leftstick** [comment]
参考[aMap.js](https://github.com/leftstick/angular-amap/blob/master/src/components/aMap.js#L60-L65)，里面的`$onChanges`钩子就能满足你的需求。

你每次在外部变更`options`时，`$onChanges`就能收到，然后你再调用`this.polyline.setOptions(changes.options.currentValue)`不就万事大吉了
