### ISSUE TITLE
marker如何调用map实例

### ISSUE THREAD

**Issue by Feather130** [leftstick/angular-amap#11]
想使用marker的自适应，但是
`
<ng-amap map-options="opts" loaded='setFitView(map)'>
       <marker ng-repeat='x in markerOpts' options="x" click="showWindow(e, marker, map)">
       </marker>
       <plugin name="ToolBar"></plugin>
</ng-amap>
`
$scope.setFitView = function(maps) {
          $scope.markerOpts.push({
                 map:maps,
                 position: [result.locations[0].M, result.locations[0].O]
}
`
只要调用maps就会报错，有什么解决方法吗？
![image](https://user-images.githubusercontent.com/10240614/32928215-e3067506-cb8b-11e7-9696-6325720bcffc.png)

**Comment by leftstick** [comment]
试试`4.2.1`
