### ISSUE TITLE
Multiple markers issue

### ISSUE THREAD

**Issue by slavoroi** [leftstick/angular-amap#2]
angular 1.4.7 and angular-amap v2 (says in the file description 1.2.0).
I tried inserting multiple markers without a title and a description (I don't want a window when i click the markers) and only one shows.
I took your demo from: https://github.com/leftstick/angular-amap/tree/2.x/demo
and changed it a little.
When i add a title and a description it works.
https://plnkr.co/edit/1fBvmQ5KREInyAZr1ahO?p=preview
Is it a bug? or am i using it wrong?

**Comment by leftstick** [comment]
It's a bug, thanks for reporting it. Fixed in `2.0.1`

**Comment by slavoroi** [comment]
can you tell me what to change? is there a version in bower with version 2.0.1?

**Comment by leftstick** [comment]
the new version is exported in both `npm` and `bower`.

You don't need change anything in your code. It's my issue. I have a `return` in `for loop` which breaks marker creation phase.

**Comment by slavoroi** [comment]
Thank you! it works :)
